carinfo:
  schedule:
    scrape-car:
      fixedDelay: 3600000
spring:
  kafka:
    producer:
      bootstrap-servers: theta-kafka:9092
    consumer:
      bootstrap-servers: theta-kafka:9092
    admin:
      properties:
        bootstrap.servers: theta-kafka:9092
  data:
    mongodb:
      database: grep-car-info
  zipkin:
    base-url: http://zipkin-service:9411

eureka:
  client:
    service-url:
      defaultZone: http://car-eureka-service:8011/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
